"""Course content for the three-day Power BI programme."""

SCHEDULE = [
    {"day": 1, "theme": "Labs 1–3 · Prepare, parameterize and combine", "focus": "Clean retail data, parameterize historical web rates and reshape a multi-page PDF receipt", "modules": "1–15"},
    {"day": 2, "theme": "Model, calculate and communicate", "focus": "Data modelling, DAX, visual design and report experience", "modules": "16–19"},
    {"day": 3, "theme": "Automate, audit and publish", "focus": "M language, audit analytics, Power BI Service and capstone", "modules": "20–23"},
]

MODULES = [
    {
        "id": 1, "code": "D1.1", "day": 1, "duration": "35 min", "lab_group": "Lab 1", "lab_step": 1,
        "title": "Install Power BI Desktop",
        "subtitle": "Use the Microsoft Store or the supported 64-bit installer",
        "outcomes": ["Choose between the Microsoft Store and direct-download routes", "Identify the supported 64-bit installer", "Launch Power BI Desktop and confirm the installation"],
        "concepts": [
            ("Microsoft Store route", "The Microsoft Store installs the latest Power BI Desktop and normally keeps it updated automatically. It also avoids a full installer download for every monthly update.", "Open the official Power BI Desktop Store page and select Install.", "Use the Store route when it is available and permitted on the learner's device."),
            ("Direct 64-bit route", "The official Microsoft Download Center provides PBIDesktopSetup_x64.exe for organizations or devices that use a standalone installer. The 32-bit edition is no longer supported.", "Select PBIDesktopSetup_x64.exe, download it and complete the setup wizard.", "Download only from Microsoft and choose the x64 installer."),
            ("Version readiness", "Power BI Desktop receives monthly updates. Keeping the trainer and learners on a recent version reduces file-compatibility and feature differences during the workshop.", "Open Help > About after installation and note the installed version.", "Use a current supported release and confirm the app opens before the lab begins."),
        ],
        "lab": ("Install and verify Power BI Desktop", "No dataset required", ["Open one of the official Microsoft download routes", "Install the Microsoft Store app or PBIDesktopSetup_x64.exe", "Launch Power BI Desktop", "Open Help > About and verify the version"], "A working Power BI Desktop installation"),
        "check": ("Which file should be selected on the direct-download route?", ["PBIDesktopSetup_x64.exe", "A 32-bit x86 installer", "A third-party repackaged installer", "Power BI Report Builder only"], 0, "The supported standalone Power BI Desktop installer is the 64-bit PBIDesktopSetup_x64.exe file."),
    },
    {
        "id": 2, "code": "D1.2", "day": 1, "duration": "45 min", "lab_group": "Lab 1", "lab_step": 2,
        "title": "Tour the Power BI Desktop interface",
        "subtitle": "Recognize the views, ribbon, canvas, panes and report pages",
        "outcomes": ["Locate the Home ribbon and common commands", "Switch between Report, Data and Model views", "Identify the report canvas, Filters, Visualizations and Data panes"],
        "concepts": [
            ("Ribbon and commands", "The ribbon organizes commands such as Get data, Transform data, New visual, New measure and Publish. Available commands can change with the selected object and view.", "Home > Get data begins the first CSV import; Home > Transform data opens Power Query Editor.", "Start by knowing where commands live, not by memorizing every button."),
            ("Report, Data and Model views", "The left rail switches between Report view for visual design, Data view for inspecting loaded tables and Model view for relationships.", "After Lab 1 is loaded, select Data view to confirm the data and Report view to begin building visuals.", "Each view answers a different development question."),
            ("Canvas, panes and pages", "The central canvas is the report design surface. Filters, Visualizations and Data panes control filtering, visual type, formatting and fields; page tabs organize the report.", "Drag a field from the Data pane to the canvas, then select a visual type from the Visualizations pane.", "Canvas in the centre, authoring panes on the right, pages at the bottom."),
        ],
        "lab": ("Identify the Power BI Desktop workspace", "Blank Power BI Desktop file", ["Locate the title bar and ribbon", "Select Report, Data and Model views on the left rail", "Point out the report canvas and the three authoring panes", "Add and rename a report page"], "A completed interface identification checklist"),
        "check": ("Where are report visuals arranged and designed?", ["On the Report view canvas", "Inside the Microsoft Store", "Only in Power Query Editor", "In the Windows download folder"], 0, "The Report view canvas is the main design surface for report visuals."),
    },
    {
        "id": 3, "code": "D1.3", "day": 1, "duration": "55 min", "lab_group": "Lab 1", "lab_step": 3,
        "title": "Lab 1: Import the retail CSV",
        "subtitle": "Read the Text/CSV preview and choose the correct loading path",
        "outcomes": ["Import a comma-separated file with Text/CSV", "Verify the file origin, delimiter, detected types and eight source columns", "Explain the implications of Load and Transform Data before choosing Transform Data"],
        "concepts": [
            ("Read the Text/CSV preview", "Home > Get data > Text/CSV displays a sample before the table enters the model. Confirm that File Origin renders characters correctly, Delimiter separates the file into eight columns and the first row has become the headers.", "For data.csv, use the detected file origin, Comma delimiter and verify InvoiceNo through Country in the preview grid.", "A neat preview confirms parsing, not the quality of every row."),
            ("Treat detected types as a first guess", "Based on first 200 rows asks Power Query to infer headers and column types from a sample. Later rows can contain different values, so identifiers, decimals and dates still require validation in Power Query Editor.", "InvoiceDate looks plausible in the preview, but the sample does not prove that every month/day value will convert correctly under the current locale.", "Automatic detection is a convenience, not a data-quality control."),
            ("Understand the source", "The original file contains 541,909 retail transaction rows and eight columns: InvoiceNo, StockCode, Description, Quantity, InvoiceDate, UnitPrice, CustomerID and Country.", "One row represents one stock item appearing on an invoice.", "Know the row meaning and expected columns before transforming the data."),
            ("Load versus Transform Data", "Load accepts the current import settings and loads the table into the Power BI model immediately. Transform Data opens Power Query Editor first, where repeatable cleaning and type steps can be reviewed before Close & Apply loads the result. Both choices keep the CSV unchanged.", "Choose Transform Data because InvoiceDate must be validated and corrected before 541,909 rows are loaded into the model.", "For this lab, select Transform Data—not Load."),
        ],
        "lab": ("Import data.csv", "Lab 1 · Retail transactions", ["Home > Get data > Text/CSV", "Select data.csv", "Confirm the file origin, comma delimiter, headers and eight columns in the preview", "Note that type detection is based on only the first 200 rows", "Select Transform Data rather than loading immediately"], "The data query open in Power Query Editor"),
        "check": ("Which preview option should be selected for this lab?", ["Transform Data", "Load without inspection", "Cancel", "Publish"], 0, "Transform Data opens Power Query Editor so the date quality issue can be investigated before loading."),
    },
    {
        "id": 4, "code": "D1.4", "day": 1, "duration": "75 min", "lab_group": "Lab 1", "lab_step": 4,
        "title": "Lab 1: Find and fix the date error",
        "subtitle": "Rebuild the type steps, validate errors and reconcile the clean query",
        "outcomes": ["Remove the unsafe automatic Changed Type step and apply InvoiceDate with the correct locale", "Use Detect Data Type, correct InvoiceNo to Text and replace the current type conversion", "Re-run Keep Errors as a temporary validation and calculate row-count and quantity statistics before loading"],
        "concepts": [
            ("Keep Errors", "Home > Keep Rows > Keep Errors retains only rows whose selected column contains an error. It is a diagnostic step for understanding the problem rather than a permanent cleanup step.", "Select InvoiceDate and keep errors to expose values that could not be converted.", "Investigate errors before removing or replacing them."),
            ("Rebuild the type sequence", "Delete the automatically created Changed Type step because it interpreted InvoiceDate before the source locale was established. First convert InvoiceDate to Date/Time using English (United States), then use Detect Data Type for the remaining columns.", "The safe order is Promoted Headers > Changed Type with Locale > Changed Type.", "Apply the locale-sensitive date conversion before broad automatic type detection."),
            ("Correct InvoiceNo without adding a conflicting step", "Detect Data Type can interpret InvoiceNo as a number from early rows, but the column also contains identifiers with letters. Change InvoiceNo to Text and choose Replace Current so the existing Changed Type step is corrected instead of stacking another competing type step.", "InvoiceNo remains Text; Quantity becomes Whole Number; UnitPrice becomes Decimal Number.", "Identifiers are labels even when many values contain only digits."),
            ("Validate, reconcile and load", "Run Keep Errors again across the typed data. If no unexpected errors remain, remove the temporary Keep Errors step so valid rows are not filtered out. Use List.NonNullCount on InvoiceNo and List.Sum on Quantity as control totals, then use Close & Apply.", "List.NonNullCount(#\"Changed Type\"[InvoiceNo]) returns the count of non-null invoice identifiers; List.Sum(#\"Changed Type\"[Quantity]) returns net quantity, including negative return rows.", "A clean query should pass both error validation and control-total reconciliation before loading."),
        ],
        "lab": ("Clean, validate and reconcile data.csv", "Lab 1 · Retail transactions", ["Use Keep Errors to inspect the initial InvoiceDate conversion failures", "Remove Keep Errors and the automatically created Changed Type step", "InvoiceDate > Data type > Using Locale > Date/Time > English (United States)", "Transform > Detect Data Type to assign the remaining types", "Change InvoiceNo to Text and select Replace Current", "Run Keep Errors again to confirm that no unexpected errors remain, then remove the validation step", "Calculate List.NonNullCount(#\"Changed Type\"[InvoiceNo]) and List.Sum(#\"Changed Type\"[Quantity])", "Home > Close & Apply and confirm the clean table is available in Power BI Desktop"], "A validated and reconciled retail table ready for the next custom-column topic"),
        "check": ("Which locale correctly interprets 1/13/2011 in this source?", ["English (United States)", "A day/month locale", "No locale is needed", "Currency locale only"], 0, "The source uses month/day/year, so English (United States) correctly interprets 1/13/2011 as 13 January 2011."),
    },
    {
        "id": 13, "code": "D1.5", "day": 1, "duration": "45 min", "lab_group": "Lab 1", "lab_step": 5,
        "title": "Create calculated and conditional Custom Columns",
        "subtitle": "Calculate invoice value and separate Sales from Sales Returns with M",
        "outcomes": ["Create InvoiceValuePQ with a row-level arithmetic expression", "Use Text.StartsWith to classify InvoiceNo values beginning with C as Sales Returns", "Explain each and if…then…else in the generated M expressions", "Assign explicit data types to both new columns and validate the results"],
        "concepts": [
            ("Custom Column", "A Custom Column evaluates an expression for every row during refresh and adds the result to the query before data reaches the model.", "InvoiceValuePQ = [Quantity] * [UnitPrice].", "Build the new column only after the source columns have valid names and types."),
            ("Generated M", "Power Query records the action as Table.AddColumn. The each keyword defines the calculation applied to the current row, while field names in square brackets read values from that row.", "Table.AddColumn(#\"Changed Type\", \"InvoiceValuePQ\", each [Quantity] * [UnitPrice]).", "Read each as: for each row, perform this expression."),
            ("Text.StartsWith and conditional logic", "Text.StartsWith returns true when a text value begins with the specified prefix. Combine it with if…then…else to bifurcate invoices: InvoiceNo values beginning with C are Sales Returns; all others are Sales.", "if Text.StartsWith([InvoiceNo], \"C\") then \"Sales Returns\" else \"Sales\".", "InvoiceNo must be Text before applying a text function."),
            ("Type and validate the results", "Each new custom column should receive an explicit data type. Set InvoiceValuePQ to Decimal Number and InvoiceType to Text, then inspect errors and representative Sales and Sales Returns rows.", "536365 is Sales; C536379 is Sales Returns; six units at 2.55 produce an InvoiceValuePQ of 15.30.", "Correct formulas still need correct output types and reasonableness checks."),
        ],
        "lab": ("Add InvoiceValuePQ and InvoiceType", "Cleaned Lab 1 retail query", ["Add Column > Custom Column and create InvoiceValuePQ as [Quantity] * [UnitPrice]", "Change InvoiceValuePQ to Decimal Number", "Add another Custom Column named InvoiceType", "Enter if Text.StartsWith([InvoiceNo], \"C\") then \"Sales Returns\" else \"Sales\"", "Change InvoiceType to Text", "Validate a normal invoice and a C-prefixed sales return", "Confirm Added Custom, Changed Type1, Added Custom1 and Changed Type2 in Applied Steps"], "Typed InvoiceValuePQ and InvoiceType columns calculated during refresh"),
        "check": ("How does the query identify Sales Returns?", ["InvoiceNo starts with C", "Quantity is always positive", "Country is blank", "UnitPrice is zero"], 0, "Text.StartsWith checks the text prefix of InvoiceNo; a leading C classifies the row as Sales Returns."),
    },
    {
        "id": 14, "code": "D1.6", "day": 1, "duration": "55 min", "lab_group": "Lab 1", "lab_step": 6,
        "title": "Compare Power Query M and DAX",
        "subtitle": "Create the same invoice value in both engines and compare the matrix results",
        "outcomes": ["Explain where and when Power Query M and DAX calculations run", "Create InvoiceValue_DAX as a DAX calculated column", "Compare InvoiceValuePQ and InvoiceValue_DAX at row and matrix levels", "Choose between an M column, DAX calculated column and DAX measure for common modelling needs"],
        "concepts": [
            ("Power Query M", "M connects to, cleans and shapes data before it enters the semantic model. Its steps run during refresh and can remove unnecessary rows or columns before model storage.", "InvoiceValuePQ is created in Power Query with each [Quantity] * [UnitPrice].", "Use M when the logic belongs to data preparation and should be completed before loading."),
            ("DAX", "DAX works inside the loaded semantic model. A DAX calculated column evaluates row by row during model refresh and is stored; a DAX measure evaluates at query time under the current filter context and is not stored as one value per row.", "InvoiceValue_DAX = data[Quantity] * data[UnitPrice] creates a stored calculated column.", "Calculated columns and measures both use DAX, but they solve different problems."),
            ("Why the two columns match", "InvoiceValuePQ and InvoiceValue_DAX use the same row-level inputs and multiplication, so they should produce the same value on every row and the same SUM by Country and InvoiceType.", "Both matrices reconcile to Sales of 10,644,560.42, Sales Returns of -896,812.49 and Total of 9,747,747.93.", "Matching results demonstrate equivalent logic, not identical execution engines."),
            ("Choosing the right engine", "Power Query M is strongest for repeatable cleaning, combining sources and reducing data before load, but it cannot respond dynamically to report filters. A DAX calculated column can use model relationships and DAX row logic after load, but it consumes model memory and remains fixed until refresh. A DAX measure is memory-efficient and responds to filter context, but it returns a result rather than a reusable row value and requires a sound model and context understanding.", "Parse InvoiceNo and remove bad rows in M; create a model-side classification as a DAX calculated column only when it depends on loaded model logic; calculate dynamic Sales, Sales Returns and Net Sales totals as measures.", "Use M for preparation, calculated columns sparingly for stored attributes, and measures for dynamic analysis."),
        ],
        "lab": ("Compare M and DAX invoice values", "Loaded Lab 1 retail table", ["In Data view, select New column", "Enter InvoiceValue_DAX = data[Quantity] * data[UnitPrice]", "Compare InvoiceValue_DAX with InvoiceValuePQ on representative rows", "Create one matrix using Country, InvoiceType and Sum of InvoiceValuePQ", "Duplicate the matrix and replace InvoiceValuePQ with InvoiceValue_DAX", "Compare country values, Sales, Sales Returns and grand totals", "Explain why identical outputs do not mean M and DAX run at the same stage"], "Two reconciled matrices and a documented M-versus-DAX decision rule"),
        "check": ("Which calculation is evaluated at report query time under filter context?", ["A DAX measure", "A Power Query custom column", "A DAX calculated column", "A CSV delimiter"], 0, "A DAX measure evaluates when a visual queries the model; M and DAX calculated columns are processed during refresh."),
    },
    {
        "id": 15, "code": "D1.7", "day": 1, "duration": "40 min", "lab_group": "Lab 2", "lab_step": 1,
        "title": "Connect to historical exchange rates on the web",
        "subtitle": "Read the X-Rates URL and import the USD historical rates page",
        "outcomes": ["Identify the base currency, amount and date query-string inputs", "Connect to the historical page with Power BI's Web source", "Explain the difference between a webpage and the table eventually extracted from it"],
        "concepts": [
            ("Read the URL", "The page address carries inputs after the question mark. from=USD selects the base currency, amount=1 fixes the base amount and date=YYYY-MM-DD selects the historical date.", "https://www.x-rates.com/historical/?from=USD&amount=1&date=2026-08-18", "Understand which part of a URL is stable and which part should become dynamic."),
            ("Web.BrowserContents", "Web.BrowserContents returns the rendered webpage content used by the following HTML extraction step. The source depends on network access, site availability and the website's published structure.", "Source = Web.BrowserContents(\"https://www.x-rates.com/historical/?from=USD&amount=1&date=2026-08-18\").", "A web query is an external dependency and must be tested for refresh reliability."),
            ("Preview before extracting", "Confirm that the selected page shows the expected historical date and the USD rates table before building selectors.", "The screenshot shows the US Dollar historical rates table and a date embedded in the URL.", "Validate the page identity before trusting the data returned from it."),
        ],
        "lab": ("Open the historical rates page", "X-Rates historical USD webpage", ["Open the X-Rates historical page in a browser", "Identify from=USD, amount=1 and date=YYYY-MM-DD", "Power BI Desktop > Get data > Web", "Enter the full dated URL", "Choose Transform Data and confirm the expected page content is available"], "A web query connected to the correct historical USD page"),
        "check": ("Which URL component should become dynamic in this lab?", ["The date value", "The https protocol", "The x-rates.com domain", "The table selector name"], 0, "The Date parameter replaces the historical date value while the source domain and page path remain stable."),
    },
    {
        "id": 16, "code": "D1.8", "day": 1, "duration": "55 min", "lab_group": "Lab 2", "lab_step": 2,
        "title": "Extract and type the HTML rates table",
        "subtitle": "Use Html.Table, promote headers and assign stable column types",
        "outcomes": ["Explain how Html.Table uses a row selector and CSS column selectors", "Promote the first extracted row to headers", "Assign Text and Decimal Number types to the currency and rate columns", "Recognize the refresh risk of website structure changes"],
        "concepts": [
            ("Html.Table selectors", "Html.Table converts selected HTML elements into rows and columns. RowSelector finds each table row; the three nth-child selectors return currency, direct rate and inverse rate.", "TABLE.tablesorter.ratesTable > * > TR > :nth-child(1) extracts the first cell from each matched row.", "CSS selectors are instructions tied to the current webpage structure."),
            ("Promote and type", "Table.PromoteHeaders turns the first extracted row into column names. Table.TransformColumnTypes then makes the currency field Text and the two rate fields numeric.", "US Dollar▲ is Text; 1.00 USD▲▼ and inv. 1.00 USD▲▼ are numbers.", "Types are part of the query contract, not cosmetic formatting."),
            ("Web extraction risk", "A redesign can change table classes, row structure or header symbols and break selectors or type steps even when the URL still opens.", "If tablesorter.ratesTable or a header changes, inspect the HTML extraction and Applied Steps before replacing errors.", "A successful refresh today does not guarantee an unmanaged webpage will remain stable."),
        ],
        "lab": ("Extract the rates table", "Rendered X-Rates HTML", ["Create the Html.Table step with the supplied row and column selectors", "Inspect Column1, Column2 and Column3", "Promote Headers", "Change the currency column to Text", "Change the direct and inverse rate columns to Decimal Number", "Confirm representative rate and inverse-rate values"], "A typed three-column historical exchange-rate query"),
        "check": ("What does :nth-child(2) extract in this query?", ["The second cell from each selected table row", "The second webpage", "Two historical dates", "The query parameter"], 0, "The selector returns the second cell for every row matched by RowSelector."),
    },
    {
        "id": 17, "code": "D1.9", "day": 1, "duration": "50 min", "lab_group": "Lab 2", "lab_step": 3,
        "title": "Create a dynamic Date parameter",
        "subtitle": "Replace the fixed date in the web URL with a Power Query parameter",
        "outcomes": ["Create and edit a Date parameter", "Concatenate the parameter into Web.BrowserContents", "Explain when Date.ToText is required", "Trace how a parameter change affects the Source step"],
        "concepts": [
            ("Parameter purpose", "A parameter stores an input separately from the query. Changing one Date value lets the same transformation steps request another historical page.", "Manage Parameters > New Parameter > Name: Date > Current Value: 2026-08-19.", "Parameters make an input configurable; they do not automatically refresh the query."),
            ("Dynamic URL", "The fixed URL is split into stable text plus the parameter value. If Date is a Text parameter formatted as YYYY-MM-DD, it can be appended directly.", "Web.BrowserContents(\"https://www.x-rates.com/historical/?from=USD&amount=1&date=\" & Date).", "Keep the parameter format exactly aligned with the website's URL requirement."),
            ("Typed Date alternative", "If the parameter is created with the Date data type rather than Text, explicitly convert it to the required URL text format.", "... & Date.ToText(Date, \"yyyy-MM-dd\").", "A Date value and a date-formatted text value are different M types."),
        ],
        "lab": ("Parameterize the historical date", "Typed X-Rates query", ["Home > Manage Parameters > New Parameter", "Name the parameter Date", "Use Text with a YYYY-MM-DD current value, or Date with Date.ToText", "Replace the fixed date in the Source URL with & Date", "Change the parameter to another valid historical date", "Refresh Preview and confirm that the requested page changes"], "One reusable query controlled by a Date parameter"),
        "check": ("What must be done when Date is a true Date-typed parameter?", ["Convert it with Date.ToText before URL concatenation", "Change every rate to text", "Remove Html.Table", "Create a DAX measure"], 0, "Web addresses are text, so a Date-typed value must be formatted before concatenation."),
    },
    {
        "id": 18, "code": "D1.10", "day": 1, "duration": "45 min", "lab_group": "Lab 2", "lab_step": 4,
        "title": "Refresh and validate the parameter-driven report",
        "subtitle": "Change the date, refresh the query and verify the displayed exchange rates",
        "outcomes": ["Edit the Date parameter from the report workflow", "Refresh and verify that values change for the requested historical date", "Build a readable currency rate table", "Explain why summing exchange rates across currencies is not a meaningful total"],
        "concepts": [
            ("Parameter change and refresh", "Editing the parameter changes the input stored in the model, but the web query must refresh before the table displays the new date's values.", "Set Date to 2026-08-19, select OK and refresh the dataset.", "Parameter edit, refresh and validation are three separate controls."),
            ("Validate the result", "Check the requested date, row count, representative currencies, numeric types and the reciprocal relationship between direct and inverse rates.", "For a currency row, direct rate multiplied by inverse rate should be approximately 1, allowing for rounding.", "Do not accept a refreshed visual without evidence that it used the intended date."),
            ("Use a table, not a summed KPI", "Rates for different currencies have different units and scales. Adding them together produces a grand total with no useful financial meaning.", "Display each currency with its direct and inverse rate and disable totals unless a defined aggregation is required.", "A visual can calculate a number that should not be interpreted."),
        ],
        "lab": ("Complete the dynamic rates report", "Parameter-driven X-Rates query", ["Add Currency, direct rate and inverse rate to a Table or Matrix", "Open Edit Parameters and enter another YYYY-MM-DD value", "Select OK and refresh", "Confirm the requested date and several currency values", "Check direct rate × inverse rate is approximately 1", "Disable meaningless grand totals across currencies", "Document the external webpage dependency"], "A validated historical-rate report controlled by the Date parameter"),
        "check": ("Why should the grand total of all currency rates normally be disabled?", ["The rates have different currency units and are not meaningfully additive", "Power BI cannot add decimals", "The parameter deletes totals", "HTML tables never contain numbers"], 0, "Exchange rates across different currencies should be compared row by row, not summed into one total."),
    },
    {
        "id": 19, "code": "D1.11", "day": 1, "duration": "40 min", "lab_group": "Lab 3", "lab_step": 1,
        "title": "Import the relevant tables from a PDF",
        "subtitle": "Inspect three detected tables and select the two invoice pages",
        "outcomes": ["Connect to Shukran.pdf with the PDF connector", "Explain why one PDF can expose several table objects", "Select Table001 and Table002 while excluding the unrelated third table", "Open both selected tables in Power Query Editor"],
        "concepts": [
            ("PDF table detection", "Pdf.Tables examines the document layout and returns detected table objects. A detected table is a connector interpretation of positioned text, not a guaranteed business table.", "Pdf.Tables(File.Contents(\"...\\Shukran.pdf\"), [Implementation=\"1.3\"]).", "Always compare detected tables with the rendered PDF pages."),
            ("Select by business relevance", "The source has three pages and three detected tables. Table001 and Table002 contain the invoice header and line items; the third page contains loyalty and terms content that is outside the required transaction dataset.", "Select Table001 (Page 1) and Table002 (Page 2) in Navigator, then choose Transform Data.", "Import only the structures needed for the defined row grain."),
            ("Expected grain", "The target table must contain one row per purchased item line, with Item Code, Item Description, Quantity, Rate, Value, TRN and Date.", "The PDF alternates item-code rows and description rows, so additional shaping is required after import.", "Define the target row before cleaning the source."),
        ],
        "lab": ("Connect to Shukran.pdf", "Lab 3 · Three-page Shukran receipt", ["Home > Get data > PDF", "Select Shukran.pdf", "Preview all three detected tables", "Select Table001 and Table002 only", "Choose Transform Data", "Confirm that two queries appear in Power Query Editor"], "Two selected PDF staging queries open for transformation"),
        "check": ("Why is the third detected table excluded?", ["It contains loyalty and terms content rather than invoice line items", "Power BI can import only two PDF tables", "Its rows are already appended", "It contains the Date parameter"], 0, "The third page is not part of the required invoice-line dataset, so loading it would mix a different business grain into the result."),
    },
    {
        "id": 20, "code": "D1.12", "day": 1, "duration": "45 min", "lab_group": "Lab 3", "lab_step": 2,
        "title": "Clean the Page 2 staging query",
        "subtitle": "Remove unusable columns and receipt-summary rows before appending",
        "outcomes": ["Assign stable types to the six extracted Page 2 columns", "Remove the two empty or misaligned columns", "Filter receipt totals and tender rows", "Rename the remaining four fields and disable load for the staging query"],
        "concepts": [
            ("Clean before append", "Table002 has six extracted columns while the target invoice structure needs four. Remove Column2 and Column3 before combining so the surviving fields align with Page 1.", "Table.RemoveColumns(#\"Changed Type\", {\"Column2\", \"Column3\"}).", "Standardize the staging schema before appending it."),
            ("Filter non-detail rows", "PDF extraction includes receipt summaries such as Total, Credit, Total Tender and Change Due. These labels are not product lines and must be excluded from the staging query.", "Table.SelectRows removes the known summary labels from Column1.", "Filtering is a business-rule step; document every excluded label."),
            ("Staging query and load", "Table002 is required as an input to Table001 but is not an independent model table. Disable Enable load after it is referenced by the append.", "Right-click Table002 (Page 2) > clear Enable load.", "Disabling load prevents a duplicate helper table without breaking the dependency."),
        ],
        "lab": ("Prepare Table002 (Page 2)", "Table002 extracted from Shukran.pdf", ["Apply the supplied column types", "Remove Column2 and Column3", "Filter Change Due, Credit, Credit Voucher, Tot Disc, Total, Total Quantity and Total Tender rows", "Rename Column1, Column4, Column5 and Column6 to Item, Quantity, Rate and Value", "Right-click Table002 and disable Enable load"], "A four-column Page 2 staging query available to the append but absent from the model"),
        "check": ("Why is Enable load disabled for Table002?", ["It is a staging query already consumed by Table001", "It contains no rows", "Append requires every source query to be hidden", "PDF queries cannot load to a model"], 0, "Table002 must still refresh, but loading it separately would duplicate data that is already appended into Table001."),
    },
    {
        "id": 21, "code": "D1.13", "day": 1, "duration": "40 min", "lab_group": "Lab 3", "lab_step": 3,
        "title": "Append Page 2 into Page 1",
        "subtitle": "Align the four fields and create one continuous receipt query",
        "outcomes": ["Rename the Page 1 fields to the same four-column schema", "Append the cleaned Page 2 staging query", "Explain how Table.Combine aligns columns by name", "Verify that the combined query contains header, item-code and description rows from both pages"],
        "concepts": [
            ("Schema alignment", "Append stacks rows and matches fields by column name. Page 1 and Page 2 must both expose Item, Quantity, Rate and Value before the operation.", "Rename Column1–Column4 in Table001 and Column1/4/5/6 in Table002 to the same names.", "Mismatched names create additional columns filled with nulls."),
            ("Append into the primary query", "Table001 is retained as the model-bound query and Table002 is added to it with Table.Combine.", "Table.Combine({#\"Renamed Columns\", #\"Table002 (Page 2)\"}).", "Append preserves rows; it does not match records like a merge."),
            ("Dependency order", "Power Query evaluates Table002 first because Table001 references it. Enable load controls model storage, not whether the staging query refreshes.", "Table002 refreshes, then Table001 appends its result and continues shaping.", "A disabled-load query can still be an active upstream dependency."),
        ],
        "lab": ("Append the two invoice pages", "Aligned Table001 and Table002 queries", ["Rename Page 1 columns to Item, Quantity, Rate and Value", "Home > Append Queries", "Append Table002 (Page 2) to Table001 (Page 1)", "Confirm the generated Table.Combine expression", "Check that the combined preview contains 40 mixed header/detail rows"], "One continuous four-column query containing both invoice pages"),
        "check": ("What does Table.Combine do in this lab?", ["Stacks Page 2 rows beneath Page 1 using matching column names", "Joins rows by Item Code", "Deletes Table002", "Loads both queries separately"], 0, "Table.Combine performs an append: it stacks the two page tables after their schemas have been aligned."),
    },
    {
        "id": 22, "code": "D1.14", "day": 1, "duration": "70 min", "lab_group": "Lab 3", "lab_step": 4,
        "title": "Extract receipt headers and pair item rows",
        "subtitle": "Use conditional columns, Fill Down, Fill Up and text functions",
        "outcomes": ["Create and fill down the TRN field", "Extract and fill down the receipt Date", "Distinguish 13-character item codes from description rows", "Fill descriptions upward to their matching item-code rows"],
        "concepts": [
            ("Carry header values to detail rows", "TRN and the timestamp occur once near the receipt header. Conditional columns retain those values only on matching rows, then Fill Down copies them to the following invoice lines.", "if Text.StartsWith([Item], \"TRN\") then [Item] else null; use Text.Contains([Item], \"GMT\") for the timestamp.", "Fill Down is appropriate when a header applies to the rows beneath it."),
            ("Convert the timestamp", "After filling the timestamp down, Text.BeforeDelimiter removes GMT and the timezone/time suffix. Converting the result to Date produces 23/09/2023.", "Text.BeforeDelimiter(_, \"GMT\") followed by type date.", "Extract only the stable date portion needed by the model."),
            ("Pair codes and descriptions", "Item-code rows contain a 13-character value and the next row contains the description. Text.Length identifies the code row; the description is retained in a new column and Fill Up moves it to the preceding code row.", "if Text.Length([Item]) = 13 then null else [Item], then Table.FillUp on Item Code.", "Fill Up is used because the descriptive value sits below the code it describes."),
        ],
        "lab": ("Reshape receipt header and detail records", "Appended Table001 query", ["Add TRN with Text.StartsWith and Fill Down", "Add the timestamp field with Text.Contains and Fill Down", "Extract text before GMT, change to Date and rename the column", "Insert Text.Length for Item", "Create Item Code/description logic using the 13-character test", "Fill Up the description column"], "Appended rows enriched with TRN, Date and paired item fields"),
        "check": ("Why is Fill Up used for Item Description?", ["The description is on the row immediately below its item code", "The TRN appears below every item", "Dates must be sorted descending", "It removes duplicate values"], 0, "The description row follows its code row, so Fill Up copies the description into the preceding item-code row before non-detail rows are filtered out."),
    },
    {
        "id": 23, "code": "D1.15", "day": 1, "duration": "55 min", "lab_group": "Lab 3", "lab_step": 5,
        "title": "Finalize and validate the PDF report",
        "subtitle": "Keep transaction rows, assign final types and reconcile the receipt",
        "outcomes": ["Filter to rows with Quantity and remove the remaining top noise rows", "Assign final numeric, date and text types", "Rename Item and Item Code to the intended business fields", "Validate 17 detail rows, quantity 20 and value AED 427.12 before loading"],
        "concepts": [
            ("Keep transaction rows", "After header values and descriptions have been propagated, rows with null Quantity are structural or descriptive rows. Filter Quantity to non-null and skip the four remaining top rows from the first-page header.", "Table.SelectRows(... each [Quantity] <> null) followed by Table.Skip(..., 4).", "Filter only after values have been propagated to the rows that will remain."),
            ("Finalize names and types", "Quantity becomes Whole Number; Rate and Value become Decimal Number; TRN and item fields remain Text; Date is Date. Remove the temporary Length column and rename the final fields.", "Rename Item Code to Item Description and Item to Item Code.", "Temporary helper columns should not enter the model."),
            ("Reconcile the output", "The completed query contains 17 line rows. The report groups repeated items into 11 displayed product rows and reconciles to total Quantity 20 and Value AED 427.12.", "Use Quantity and Value as the primary receipt controls. The displayed Sum of Rate 484.90 is not an additive financial total because Rate is a unit price.", "A visually plausible table is not complete until it reconciles to the receipt."),
        ],
        "lab": ("Load and validate the completed receipt", "Final Table001 query", ["Filter Quantity to non-null", "Remove the first four remaining header rows", "Set Quantity, Rate, Value, TRN, Date and item types", "Remove Length", "Rename Item Code to Item Description and Item to Item Code", "Confirm Table002 has load disabled", "Close & Apply", "Build the item summary table and reconcile Quantity 20 and Value AED 427.12"], "One loaded 17-row receipt table and a reconciled item summary report"),
        "check": ("Which controls best validate the completed receipt?", ["Total Quantity 20 and total Value AED 427.12", "Sum of Item Codes and average TRN", "Three loaded model tables", "The number of Applied Steps only"], 0, "Quantity and transaction value reconcile directly to the source receipt; a sum of unit rates is not a meaningful receipt total."),
    },
    {
        "id": 5, "code": "D2.1", "day": 2, "duration": "90 min",
        "title": "Design a finance-ready data model",
        "subtitle": "Build a star schema with predictable filter flow",
        "outcomes": ["Separate facts from dimensions", "Create one-to-many relationships", "Use a dedicated date table"],
        "concepts": [
            ("Star schema", "A fact table stores events and numeric observations; dimensions describe the people, products, accounts, dates and entities used to group them.", "Sales sits at invoice-line grain and connects to Date, Product, Customer and Geography dimensions.", "A simple star usually produces simpler DAX and predictable filtering."),
            ("Cardinality and filter direction", "The dimension key is unique on the one side; repeated foreign keys appear on the many side. Single-direction filtering from dimension to fact is the safest default.", "One Product row filters many Sales rows through ProductKey.", "Many-to-many and bidirectional filters need a clear business reason."),
            ("Date table", "A complete, contiguous date table enables consistent year, quarter, month and time-intelligence calculations.", "Relate Date[Date] to Sales[InvoiceDate] and sort Month Name by Month Number.", "One governed calendar is better than several hidden date tables."),
        ],
        "lab": ("Model sales, budget and returns", "Sales, target, product and calendar tables", ["Classify fact and dimension tables", "Create unique dimension keys", "Build relationships and test filter flow", "Create and mark a date table"], "A clean star-schema model diagram"),
        "check": ("What is the preferred default filter direction in a star schema?", ["From fact to every dimension", "Both directions everywhere", "From dimension to fact", "No relationships"], 2, "Single-direction filtering from dimensions to facts is predictable and reduces ambiguity."),
    },
    {
        "id": 6, "code": "D2.2", "day": 2, "duration": "120 min",
        "title": "DAX measures and filter context",
        "subtitle": "Translate finance logic into reusable business calculations",
        "outcomes": ["Create explicit measures", "Explain row and filter context", "Use CALCULATE, iterators and safe division"],
        "concepts": [
            ("Measures versus calculated columns", "A calculated column is evaluated row by row during refresh and stored. A measure is evaluated at query time under the current filter context.", "Net Sales should normally be a measure because it must respond to country, product and date filters.", "Use columns for row attributes; use measures for aggregations."),
            ("CALCULATE", "CALCULATE evaluates an expression under a modified filter context. It is the foundation of ratios, period comparisons and conditional business logic.", "Prior Year Sales = CALCULATE([Sales], SAMEPERIODLASTYEAR('Date'[Date])).", "Read CALCULATE as: evaluate this expression under these filters."),
            ("Iterators and DIVIDE", "X-functions such as SUMX evaluate an expression row by row over a table. DIVIDE safely handles zero or blank denominators.", "Margin % = DIVIDE([Gross Margin], [Net Sales]).", "Correct totals depend on understanding evaluation context, not formatting."),
        ],
        "lab": ("Create a management measure pack", "Sales, cost, returns and budget model", ["Create base measures for sales, cost and quantity", "Calculate gross margin and margin percentage", "Add actual-versus-budget variance", "Validate totals under several filters"], "A documented library of reusable measures"),
        "check": ("Which function changes filter context before evaluating an expression?", ["FORMAT", "CALCULATE", "CONCATENATE", "RELATEDTABLE only"], 1, "CALCULATE evaluates an expression under modified filters."),
    },
    {
        "id": 7, "code": "D2.3", "day": 2, "duration": "75 min",
        "title": "Visual analytics that communicates",
        "subtitle": "Match visual form to the finance question",
        "outcomes": ["Choose visuals by analytical purpose", "Apply accessible formatting", "Avoid misleading scales and clutter"],
        "concepts": [
            ("Purpose before chart", "Use bars for comparison, lines for trends, cards for headline values, matrices for detailed statements and scatter plots for relationships.", "A monthly revenue trend belongs in a line chart; country variance comparisons belong in sorted bars.", "Choose the visual that makes the pattern easiest to see."),
            ("Visual hierarchy", "A page should guide attention from key outcomes to drivers and detail through position, size, spacing and limited accent colour.", "Place KPI cards and the primary variance visual in the first viewing area; keep reconciliation detail lower.", "Emphasis should reflect decision importance."),
            ("Honest design", "Use appropriate baselines, meaningful units, readable labels and accessible contrast. Avoid decorative elements that compete with data.", "A bar chart starting near the maximum exaggerates a small variance; a line chart may legitimately use a focused range when clearly labelled.", "Clarity is a control, not decoration."),
        ],
        "lab": ("Build an executive performance page", "Sales and budget model", ["Select one headline decision", "Create KPI, trend and driver visuals", "Apply consistent number formats and titles", "Test cross-filtering and mobile readability"], "A one-page executive performance report"),
        "check": ("Which visual is usually best for comparing variance across categories?", ["Sorted bar chart", "Gauge for every category", "Decorative map", "Unlabelled pie with many slices"], 0, "Sorted bars make category magnitude and rank easy to compare."),
    },
    {
        "id": 8, "code": "D2.4", "day": 2, "duration": "75 min",
        "title": "Design the report experience",
        "subtitle": "Create purposeful navigation, interaction and narrative",
        "outcomes": ["Control interactions and drill paths", "Use tooltips, bookmarks and buttons", "Design a coherent multi-page story"],
        "concepts": [
            ("Interaction design", "Cross-filtering, slicers and drillthrough should answer natural follow-up questions without creating unexpected state.", "Selecting a country filters the trend and category drivers; drillthrough opens its transaction detail.", "Every interaction should have an understandable result."),
            ("Bookmarks and buttons", "Bookmarks capture report state and can support navigation, reset actions and alternate views. Buttons make the action discoverable.", "A Reset Filters button returns the page to an approved default state.", "Use bookmarks for a user journey, not as a substitute for a sound model."),
            ("Narrative pages", "Give each page a specific audience and question. Use consistent navigation and progressive detail.", "Overview → Margin drivers → Customer exceptions → Transaction detail.", "One page, one primary question."),
        ],
        "lab": ("Turn pages into a guided report", "Executive dashboard PBIX", ["Define the question for each page", "Configure interactions and drillthrough", "Add tooltip and navigation pages", "Create reset and view-toggle bookmarks"], "A guided, testable report experience"),
        "check": ("What is a strong use for a bookmark?", ["Repairing broken relationships", "Capturing a reset or alternate report state", "Replacing source data", "Creating a database index"], 1, "Bookmarks capture report state and are useful for navigation, reset and alternate views."),
    },
    {
        "id": 9, "code": "D3.1", "day": 3, "duration": "75 min",
        "title": "Power Query M and reusable logic",
        "subtitle": "Read generated code and create maintainable transformations",
        "outcomes": ["Read let/in expressions", "Use variables and functions", "Create parameters for portable queries"],
        "concepts": [
            ("let and in", "An M query defines named steps inside a let block and returns the expression named after in. Each step can reference an earlier step.", "let Source = Excel.Workbook(...), Data = Source{[Item=\"Sales\"]}[Data] in Data", "The final in expression controls what the query returns."),
            ("Functions", "A custom function packages parameterized logic that can be invoked for many files or values.", "A TransformFile function applies the same column cleanup to every monthly workbook.", "Functions remove repeated manual transformation logic."),
            ("Parameters", "Parameters externalize changing values such as folder paths, cut-off dates and environment names.", "Switch a SourcePath parameter from the trainer folder to the learner folder without rewriting steps.", "Separate configuration from transformation logic."),
        ],
        "lab": ("Parameterize a folder ingestion query", "Monthly finance extracts", ["Open Advanced Editor and trace each step", "Create a folder-path parameter", "Convert cleanup logic into a function", "Invoke it across files and validate schema"], "A portable, reusable M query"),
        "check": ("In an M query, what does the expression after ‘in’ do?", ["Selects the returned step", "Creates a visual", "Publishes a workspace", "Changes DAX context"], 0, "The expression after in is the value returned by the query."),
    },
    {
        "id": 10, "code": "D3.2", "day": 3, "duration": "105 min",
        "title": "Audit analytics and anomaly detection",
        "subtitle": "Use Power BI to surface risk indicators without overstating evidence",
        "outcomes": ["Design exception tests", "Apply Benford analysis appropriately", "Separate indicators from conclusions"],
        "concepts": [
            ("Exception tests", "Rules can flag weekends, duplicates, round values, unusual users, missing masters or entries near approval limits.", "Flag journal entries posted on weekends with round amounts above a defined threshold.", "A flag prioritizes review; it does not prove wrongdoing."),
            ("Benford's Law", "In suitable naturally occurring datasets, leading digits often follow a predictable logarithmic distribution. Compare observed and expected frequencies, then investigate material deviations.", "Analyze the first digit of positive transaction amounts after excluding assigned numbers and constrained ranges.", "Suitability, population size and business context come before the chart."),
            ("Evidence trail", "An audit dashboard should allow reviewers to move from summary risk signals to the underlying transaction and document the test definition.", "A high-risk supplier count drills to invoices, approvers, dates and source identifiers.", "Reproducibility is part of audit quality."),
        ],
        "lab": ("Create an audit exception dashboard", "General ledger and payment transactions", ["Define risk questions and exclusion rules", "Build weekend, duplicate and round-value flags", "Compare observed leading digits with Benford expectations", "Create drillthrough to transaction evidence"], "An exception dashboard with a documented methodology"),
        "check": ("What does a Benford deviation establish by itself?", ["Fraud is proven", "The records must be deleted", "A population may warrant investigation", "The audit is complete"], 2, "A deviation is an analytical indicator that may justify further investigation; it is not proof."),
    },
    {
        "id": 11, "code": "D3.3", "day": 3, "duration": "75 min",
        "title": "Publish, secure and refresh",
        "subtitle": "Move from a desktop file to governed organisational use",
        "outcomes": ["Organize workspaces and apps", "Configure refresh and gateways", "Apply row-level security and lineage thinking"],
        "concepts": [
            ("Workspace and app", "A workspace is the collaboration and content-management area for developers. An app is a curated distribution package for consumers.", "Finance develops and validates in a controlled workspace, then publishes an app to managers.", "Separate authoring access from consumption access."),
            ("Refresh and gateway", "Cloud sources can often refresh directly. On-premises sources generally need a gateway that securely brokers queries without copying credentials into the report.", "A scheduled refresh accesses an on-premises SQL finance database through an enterprise gateway.", "Test credentials, privacy levels and refresh ownership before handover."),
            ("Security and governance", "Row-level security filters model rows by role or user. Sensitivity, endorsement, lineage and controlled permissions support trusted reuse.", "Regional managers see only their entities through a user-to-region mapping table.", "RLS controls rows; it is not a substitute for workspace permission design."),
        ],
        "lab": ("Prepare a deployment runbook", "Completed management report", ["Choose workspace roles and app audiences", "Define refresh ownership and gateway needs", "Design and test an RLS mapping", "Record endorsement, lineage and support responsibilities"], "A practical deployment and governance checklist"),
        "check": ("What is the usual purpose of a Power BI app?", ["Curated distribution to consumers", "Editing source CSV files", "Writing M without Desktop", "Replacing all workspace permissions"], 0, "An app distributes a curated collection of content to a defined audience."),
    },
    {
        "id": 12, "code": "D3.4", "day": 3, "duration": "120 min",
        "title": "Capstone: management and audit dashboard",
        "subtitle": "Integrate the complete workflow and present a defensible result",
        "outcomes": ["Deliver an end-to-end Power BI solution", "Reconcile outputs to source", "Explain design and control decisions"],
        "concepts": [
            ("End-to-end discipline", "A strong solution connects a defined decision to controlled ingestion, a sound model, validated measures and an intentional report experience.", "The team traces one KPI from source row through Power Query, relationship, DAX and final visual.", "The chain is only as reliable as its weakest link."),
            ("Validation", "Reconcile row counts, control totals, filter behaviour, edge cases and representative transactions. Record assumptions and known limitations.", "Net sales agrees to the supplied control total, including returns and blank product mappings.", "Validate both numbers and behaviour."),
            ("Presentation", "Explain the question, model, insight, recommended action and governance plan. Demonstrate drill paths and respond to challenge.", "Present the margin shortfall, isolate its drivers and show the evidence page supporting action.", "A dashboard presentation should end with a decision or next step."),
        ],
        "lab": ("Build and present the final solution", "Sales, returns, budget and audit datasets", ["Profile and transform the supplied data", "Create a star model and measure pack", "Design management and audit report pages", "Reconcile, peer review and present the recommendation"], "A complete PBIX solution and five-minute presentation"),
        "check": ("Which is the strongest final validation?", ["The colour theme looks consistent", "One card has the expected number", "Source totals, filter behaviour and transactions reconcile", "The PBIX opens without errors"], 2, "Reliable validation covers totals, behaviour and representative records, not only appearance."),
    },
]

ASSESSMENT = [
    ("Which standalone Power BI Desktop installer is supported?", ["PBIDesktopSetup_x64.exe", "A 32-bit x86 installer", "A third-party package", "Power BI Report Builder"], 0),
    ("Which Power BI Desktop view is used to arrange report visuals?", ["Report view", "Microsoft Store view", "Power Query error view", "Download Center view"], 0),
    ("Which CSV preview action opens Power Query Editor before loading?", ["Transform Data", "Publish", "Load without inspection", "Cancel"], 0),
    ("What does Keep Errors do in Power Query?", ["Keeps only rows containing errors in the selected columns", "Silently fixes every error", "Publishes the table", "Changes all columns to text"], 0),
    ("Which operation stacks monthly files vertically?", ["Merge", "Append", "Pivot chart", "Drillthrough"], 1),
    ("Which join returns unmatched rows from the first table?", ["Left anti", "Inner", "Cross", "Right outer only"], 0),
    ("In a star schema, where are transaction amounts normally stored?", ["Fact table", "Date dimension", "Tooltip page", "Workspace"], 0),
    ("The unique Product table sits on which side of a Product-to-Sales relationship?", ["Many", "One", "Inactive only", "Disconnected"], 1),
    ("Why use a dedicated date table?", ["To enable consistent time analysis", "To store passwords", "To replace all dimensions", "To make bars yellow"], 0),
    ("Which DAX function changes filter context?", ["CALCULATE", "UPPER", "FORMAT", "LEN"], 0),
    ("Which expression safely calculates a ratio?", ["DIVIDE([Margin], [Sales])", "[Margin] & [Sales]", "FORMAT([Margin])", "COUNTROWS([Margin])"], 0),
    ("A measure is evaluated primarily when?", ["At query time under filter context", "Only when typed", "Only during installation", "Inside Power Query"], 0),
    ("Which visual best shows a time trend?", ["Line chart", "Gauge", "Pie with 20 slices", "Single card"], 0),
    ("What can a drillthrough page provide?", ["Context-specific detail", "A new database", "Automatic source correction", "A gateway"], 0),
    ("What follows the `in` keyword in M?", ["The returned expression", "A DAX measure", "A workspace role", "A visual theme"], 0),
    ("A custom M function is useful for what?", ["Repeating parameterized transformations", "Assigning licences", "Creating RLS roles", "Drawing shapes"], 0),
    ("What does a Benford deviation prove?", ["Nothing by itself; it signals review", "Fraud", "A duplicate", "The model is correct"], 0),
    ("What usually connects on-premises data to scheduled refresh?", ["Gateway", "Bookmark", "Tooltip", "Mobile layout"], 0),
    ("What does row-level security control?", ["Which model rows a user can see", "Report colours", "Source file names", "Licence pricing"], 0),
    ("What is essential before presenting the capstone?", ["Reconcile totals and test behaviour", "Add animations", "Hide all assumptions", "Remove source identifiers"], 0),
]

RESOURCES = [
    ("Lab 1 · Original retail CSV", "The complete 541,909-row data.csv file used for importing, error detection and locale correction", "lab-1-importing-data-basics.zip"),
    ("Lab 1 · Completed solution PBIX", "Completed Lab 1 reference covering setup, CSV preparation, custom columns, Sales Returns classification and the M-versus-DAX comparison", "completed-lab-1.pbix"),
    ("Lab 2 · Completed solution PBIX", "Completed parameter-driven historical exchange-rates query and report for comparison after finishing all four Lab 2 steps", "completed-lab-2.pbix"),
    ("Lab 3 · Original Shukran receipt PDF", "The three-page receipt used to detect, append and reshape the two invoice-page tables", "lab-3-shukran.pdf"),
    ("Lab 3 · Completed solution PBIX", "Completed PDF import with Page 2 staging, append, header/detail extraction, disabled staging load and reconciled report", "completed-lab-3.pbix"),
    ("Day 1 · Data preparation labs", "Queries, cleaning, folder ingestion and combining exercises", "day-1-data-preparation-labs.zip"),
    ("Day 2 · Model and DAX labs", "Model-building, calculations and report-design exercises", "day-2-model-dax-labs.zip"),
    ("Day 3 · Audit analytics labs", "Audit tests, Benford analysis and capstone inputs", "day-3-audit-analytics-labs.zip"),
    ("Course reference · Power BI module", "Detailed reference material supporting the learning pathway", "icai-aicitss-module-2-power-bi.pdf"),
    ("Sales dashboard · Starter PBIX", "Starter file for guided modelling and visual exercises", "sales-dashboard-starter.pbix"),
    ("Sales dashboard · Reference PBIX", "Completed reference solution for comparison", "sales-dashboard-reference.pbix"),
    ("Sales and returns · Reference PBIX", "Model with sales and returns analysis", "sales-and-returns-reference.pbix"),
    ("Merge lab · Reference PBIX", "Compact completed merge example", "merge-lab-reference.pbix"),
    ("Executive dashboard · Completed PBIX", "Completed dashboard for report-experience practice", "power-bi-dashboard-completed.pbix"),
    ("Benford audit · Reference PBIX", "Completed leading-digit analysis example", "benford-audit-reference.pbix"),
    ("Bonus business challenge", "Additional datasets and open-ended tasks", "bonus-business-challenge-pack.zip"),
]


TOOL_LABS = {
    1: {
        "screen_title": "Install Power BI Desktop from Microsoft",
        "screens": [
            ("Microsoft Store", "00-power-bi-store-install.png", "The official Microsoft Store listing with the Install button highlighted. Source: Microsoft Learn.", ["Select Install on the official Power BI Desktop listing", "The Store route normally keeps Power BI Desktop updated automatically", "No third-party download site is required"]),
            ("Direct 64-bit installer", "00-power-bi-x64-download.png", "The Microsoft Download Center selection screen with PBIDesktopSetup_x64.exe selected. Source: Microsoft Learn.", ["Choose PBIDesktopSetup_x64.exe", "The 32-bit edition is no longer supported", "Run the downloaded installer and complete the setup wizard"]),
        ],
        "click_path": ["Preferred route: open the official Microsoft Store listing and select Install", "Alternative route: open the Microsoft Download Center", "Select PBIDesktopSetup_x64.exe and complete installation", "Launch Power BI Desktop and verify Help > About"],
        "task": "Install Power BI Desktop using one approved Microsoft route and confirm that the application opens successfully.",
        "evidence": "A working Power BI Desktop installation and the installed version number",
    },
    2: {
        "screen_title": "Locate the main Power BI Desktop components",
        "screens": [
            ("Power BI Desktop interface", "01-power-bi-desktop-interface.png", "A full Power BI Desktop Report view showing the ribbon, view rail, canvas, authoring panes and page tabs. Source: Microsoft Learn.", ["Ribbon and Get data commands are across the top", "Report, Data and Model views are on the left rail", "The report canvas occupies the centre", "Filters, Visualizations and Data panes are on the right", "Report pages appear along the bottom"]),
        ],
        "click_path": ["Select Home and identify Get data and Transform data", "Select Report view on the left rail", "Locate the report canvas and right-side authoring panes", "Select Data view and Model view", "Add and rename a report page at the bottom"],
        "task": "Use the screenshot and your open application to identify each major interface component without assistance.",
        "evidence": "A completed interface checklist covering ribbon, views, canvas, panes and pages",
    },
    3: {
        "screen_title": "Understand the CSV preview, then open Power Query Editor",
        "screens": [
            ("Text/CSV preview", "02-text-csv-preview.png", "The data.csv preview shown before the file is loaded or opened in Power Query Editor.", ["File Origin controls how characters are decoded", "Comma must split the file into eight expected columns", "Based on first 200 rows is an inferred type sample, not a full quality check", "Load imports immediately using the current settings", "Transform Data opens Power Query Editor before the result is loaded", "Neither choice changes the source CSV"]),
            ("Get data from the Home ribbon", "01-power-bi-desktop-interface.png", "The Home ribbon contains Get data and Transform data. Source: Microsoft Learn.", ["Select Get data", "Choose Text/CSV", "Select data.csv", "Use the preview to verify the file before continuing"]),
            ("Power Query Editor", "03-power-query-editor.png", "The course data open in Power Query Editor with the ribbon, preview, formula bar and Applied Steps visible.", ["The query named data appears on the left", "The centre grid previews the eight source columns", "Applied Steps record each transformation", "The formula bar shows the generated M expression"]),
        ],
        "click_path": ["Power BI Desktop > Home > Get data > Text/CSV", "Browse to the Lab 1 CSV folder and select data.csv", "Confirm the file origin, comma delimiter, headers and eight columns", "Recognize that the displayed types are inferred from the first 200 rows", "Select Transform Data", "Verify that the data query opens in Power Query Editor"],
        "task": "Import the original Lab 1 data.csv file and stop in Power Query Editor before loading it.",
        "evidence": "The data query visible in Power Query Editor with all eight source columns",
    },
    4: {
        "screen_title": "Correct types, validate the query and reconcile before loading",
        "screens": [
            ("Completed Lab 1 query", "04-lab1-completed-power-query.png", "The completed Lab 1 PBIX shows the locale-aware date conversion and corrected Changed Type step in the final Applied Steps sequence.", ["Changed Type with Locale comes before the broad Changed Type step", "InvoiceNo is stored as Text", "Keep Errors is absent because it was only a temporary validation step", "The completed query also contains the later custom-column steps", "The screenshot was captured directly from Completed Lab_1.pbix"]),
        ],
        "click_path": ["Select InvoiceDate and convert it to Date/Time to expose the error", "Home > Keep Rows > Keep Errors and inspect values such as 1/13/2011", "Remove Keep Errors and the automatic Changed Type step", "InvoiceDate > Data type > Using Locale > Date/Time > English (United States)", "Transform > Detect Data Type", "Change InvoiceNo to Text and select Replace Current", "Run Keep Errors again, confirm no unexpected errors and remove the step", "Evaluate the InvoiceNo non-null count and Quantity sum", "Home > Close & Apply and confirm the table appears in Power BI Desktop"],
        "task": "Rebuild the query's type sequence, validate all typed columns with Keep Errors, reconcile the two statistics and load the clean table.",
        "evidence": "A loaded table with the correct locale and column types, no unexplained errors, and recorded row-count and quantity controls",
    },
    13: {
        "screen_title": "Add calculated and conditional columns in Power Query Editor",
        "screens": [
            ("Completed Lab 1 custom columns", "04-lab1-completed-power-query.png", "The supplied completed PBIX displays InvoiceType and InvoiceValuePQ together with every generated Applied Step.", ["InvoiceValuePQ multiplies Quantity by UnitPrice for each row", "InvoiceType displays Sales for ordinary invoice numbers", "Added Custom and Changed Type steps are visible in the final query", "InvoiceValuePQ is Decimal Number and InvoiceType is Text", "The screenshot was captured directly from Completed Lab_1.pbix"]),
        ],
        "click_path": ["Power Query Editor > Add Column > Custom Column", "Create InvoiceValuePQ with [Quantity] * [UnitPrice] and set it to Decimal Number", "Add a second Custom Column named InvoiceType", "Enter if Text.StartsWith([InvoiceNo], \"C\") then \"Sales Returns\" else \"Sales\"", "Set InvoiceType to Text", "Confirm all four Added Custom and Changed Type steps", "Check representative Sales and Sales Returns rows before Close & Apply"],
        "task": "Create InvoiceValuePQ and use Text.StartsWith to bifurcate the retail rows into Sales and Sales Returns.",
        "evidence": "Typed InvoiceValuePQ and InvoiceType columns with correctly classified normal and C-prefixed invoice numbers",
    },
    14: {
        "screen_title": "Compare an M custom column with a DAX calculated column",
        "screens": [
            ("DAX calculated column", "04-invoice-value-dax-column.png", "Data view showing InvoiceValue_DAX beside InvoiceValuePQ. Both columns use Quantity multiplied by UnitPrice and display matching row values.", ["The formula bar contains DAX, not M", "InvoiceValue_DAX is created after the table has loaded into the model", "InvoiceValuePQ arrived from Power Query", "Both are stored row-level columns", "Matching row values validate equivalent business logic"]),
            ("Matrix comparison", "04-m-query-dax-matrix-comparison.png", "Two matrices aggregate the Power Query and DAX columns by Country and InvoiceType. Their sorting differs, but the country values and grand totals reconcile.", ["Rows use Country", "Columns use InvoiceType: Sales and Sales Returns", "One matrix sums InvoiceValuePQ and the other sums InvoiceValue_DAX", "Both grand totals equal 9,747,747.93", "Visual equality does not mean the calculations execute in the same engine"]),
        ],
        "click_path": ["Data view > New column", "Enter InvoiceValue_DAX = data[Quantity] * data[UnitPrice]", "Compare InvoiceValuePQ and InvoiceValue_DAX on several Sales and Sales Returns rows", "Report view > add a Matrix visual", "Rows > Country; Columns > InvoiceType; Values > Sum of InvoiceValuePQ", "Duplicate the matrix and replace the value with Sum of InvoiceValue_DAX", "Reconcile country values and grand totals", "State when M, a DAX calculated column or a DAX measure should be used"],
        "task": "Reproduce both matrices and explain why the results match even though M and DAX execute at different stages.",
        "evidence": "Matching row calculations, reconciled matrix totals and a correct M-versus-DAX comparison",
    },
    15: {
        "screen_title": "Identify the dynamic inputs in the historical rates URL",
        "screens": [("X-Rates historical page", "05-lab2-xrates-historical-page.png", "The USD historical exchange-rates page with from, amount and date values visible in the address bar.", ["from=USD fixes the base currency", "amount=1 fixes the base amount", "date=YYYY-MM-DD is the value that will become a parameter", "The expected USD historical rates table is visible before extraction"])],
        "click_path": ["Open the historical X-Rates URL", "Verify from=USD and amount=1", "Choose a valid historical date", "Power BI Desktop > Get data > Web", "Paste the fixed dated URL and choose Transform Data"],
        "task": "Connect Power BI to the correct USD historical rates webpage and identify the input that will become dynamic.",
        "evidence": "A Source query connected to the expected historical USD page",
    },
    16: {
        "screen_title": "Extract the three-column rates table with Html.Table",
        "screens": [("Completed Lab 2 Power Query Editor", "05-lab2-power-query-editor.png", "The supplied completed PBIX shows the ExchangeRates query as a typed three-column X-Rates table with the actual HTML extraction steps.", ["The preview contains currency, direct rate and inverse rate", "Extracted Table From Html is visible in Applied Steps", "Promoted Headers replaces Column1–Column3", "Changed Type assigns Text and numeric types", "The screenshot was captured directly from Completed Lab_2.pbix"])],
        "click_path": ["Inspect the Source page in Power Query", "Apply the supplied Html.Table selectors", "Verify the three extracted columns", "Promote Headers", "Assign Text and Decimal Number types", "Validate a direct and inverse rate pair"],
        "task": "Convert the rendered webpage into a typed three-column exchange-rates table.",
        "evidence": "An extracted rates query with currency, direct rate and inverse rate columns",
    },
    17: {
        "screen_title": "Control the web query with the Date parameter",
        "screens": [("Date parameter in Power Query", "05-lab2-date-parameter-pq.png", "The Date parameter inside the supplied completed PBIX exposes one editable current value used by ExchangeRates.", ["Date is the single changing input", "The current value uses YYYY-MM-DD", "Manage Parameter opens the parameter definition", "The ExchangeRates query reads this value when its Source step refreshes", "The screenshot was captured directly from Completed Lab_2.pbix"])],
        "click_path": ["Power Query Editor > Manage Parameters > New Parameter", "Name > Date", "Set the current value", "Edit the Source URL to end with & Date", "For a Date-typed parameter use Date.ToText(Date, \"yyyy-MM-dd\")", "Refresh Preview and verify the requested page"],
        "task": "Replace the hard-coded web date with a configurable Power Query parameter.",
        "evidence": "A Source step whose URL is generated from the Date parameter",
    },
    18: {
        "screen_title": "Refresh and validate the parameter-driven exchange-rate table",
        "screens": [("Completed Lab 2 report", "05-lab2-completed-report.png", "The report page in the supplied completed PBIX displays the refreshed ExchangeRates table.", ["The completed table lists each currency with direct and inverse rates", "Change Date and refresh before validating new values", "Direct and inverse rates should be approximately reciprocal", "The current visual contains totals; explain that adding rates across currencies is not financially meaningful", "The screenshot was captured directly from Completed Lab_2.pbix"])],
        "click_path": ["Add the three fields to a Table or Matrix", "Edit Parameters > enter another date", "Select OK and refresh", "Validate the date and representative currencies", "Check direct × inverse is approximately 1", "Turn off meaningless currency-rate totals"],
        "task": "Demonstrate a successful parameter change and validate the resulting historical exchange rates.",
        "evidence": "A refreshed rate table for the selected date with validation checks recorded",
    },
    19: {
        "screen_title": "Inspect the three PDF pages and select the two invoice tables",
        "screens": [
            ("PDF page 1", "06-lab3-pdf-page-1.png", "Page 1 contains the receipt header and the first group of item-code and description rows.", ["The timestamp and TRN appear once near the header", "Item codes and descriptions occupy separate rows", "Quantity, Rate and Value appear beside code rows", "This page is imported as Table001"]),
            ("PDF page 2", "06-lab3-pdf-page-2.png", "Page 2 continues the purchased items and ends with receipt totals and tender information.", ["This page is imported as Table002", "Item rows continue from Page 1", "Total Quantity, Total, Credit and Change Due are not product rows", "The Page 2 query must be cleaned before append"]),
            ("PDF page 3", "06-lab3-pdf-page-3.png", "Page 3 contains Shukran loyalty details, terms and store information rather than invoice line items.", ["The connector detects a third table here", "Its business grain differs from the target invoice lines", "It is intentionally excluded from this lab", "Selecting fewer tables is a data-modelling decision, not a connector limitation"]),
        ],
        "click_path": ["Power BI Desktop > Home > Get data > PDF", "Select Shukran.pdf", "Preview all three detected tables", "Select Table001 and Table002", "Leave the unrelated third table unselected", "Choose Transform Data"],
        "task": "Import only the two detected tables that contain the invoice header and line items.",
        "evidence": "Table001 (Page 1) and Table002 (Page 2) visible as separate queries in Power Query Editor",
    },
    20: {
        "screen_title": "Clean Table002 as a Page 2 staging query",
        "screens": [("Table002 (Page 2)", "06-lab3-table002-clean-query.png", "The supplied completed PBIX shows Page 2 reduced to Item, Quantity, Rate and Value before it is appended.", ["Column2 and Column3 have been removed", "Receipt summary labels have been filtered out", "The remaining fields are renamed to the shared append schema", "Table002 is italic because Enable load is disabled", "The query still refreshes because Table001 references it"])],
        "click_path": ["Select Table002 (Page 2)", "Apply the six supplied source types", "Remove Column2 and Column3", "Filter receipt-total and tender labels from Column1", "Rename the four remaining fields", "Right-click Table002 and clear Enable load"],
        "task": "Create a reusable Page 2 staging query with the same four fields expected by Page 1.",
        "evidence": "A four-column Table002 staging query that refreshes but does not load independently",
    },
    21: {
        "screen_title": "Append the cleaned Page 2 rows into Table001",
        "screens": [("Appended Query step", "06-lab3-appended-query.png", "The completed PBIX at the Appended Query step shows Table.Combine stacking the two aligned page queries.", ["Table001 remains the primary model-bound query", "Table002 is referenced by name in Table.Combine", "Rows are stacked rather than matched by a key", "The preview contains mixed header, code and description rows that still require shaping", "The two Page 2 source columns align because their names were standardized first"])],
        "click_path": ["Rename Table001 fields to Item, Quantity, Rate and Value", "Home > Append Queries", "Choose Table002 (Page 2)", "Confirm Table.Combine in the formula bar", "Verify rows from both pages in the 40-row preview"],
        "task": "Create one continuous receipt query by appending Page 2 beneath Page 1.",
        "evidence": "An Appended Query step in Table001 with both pages represented in one four-column preview",
    },
    22: {
        "screen_title": "Turn mixed PDF rows into transaction records",
        "screens": [("Completed Table001 query", "06-lab3-table001-final-query.png", "The supplied completed PBIX shows the final item-level output and the full sequence used to propagate TRN, Date and descriptions.", ["TRN and Date are filled down from receipt-header rows", "Descriptions are filled up to the preceding 13-character item-code rows", "Temporary Length supports the code/description test and is later removed", "Only transaction rows remain", "The final fields are Item Code, Quantity, Rate, Value, TRN, Date and Item Description"])],
        "click_path": ["Create TRN with Text.StartsWith and Fill Down", "Create the timestamp field with Text.Contains and Fill Down", "Extract text before GMT and convert to Date", "Insert Text.Length for Item", "Create the description helper using the 13-character test", "Fill Up the description values", "Filter to rows with Quantity"],
        "task": "Reshape the alternating receipt layout into one complete row per purchased item line.",
        "evidence": "Item rows enriched with TRN, Date and the matching Item Description",
    },
    23: {
        "screen_title": "Validate the loaded Lab 3 receipt report",
        "screens": [
            ("Completed report", "06-lab3-completed-report.png", "The report page in the supplied completed PBIX groups the 17 transformed lines into an item summary.", ["The displayed products reconcile to total Quantity 20", "Total Value reconciles to AED 427.12", "Repeated item codes aggregate into 11 displayed product rows", "Sum of Rate 484.90 is shown but unit rates are not a meaningful additive control", "Only Table001 appears in the model Data pane"]),
            ("Final Power Query output", "06-lab3-table001-final-query.png", "The final model-bound query contains 17 item-level rows and seven typed columns.", ["Table001 is loaded", "Table002 remains an upstream staging dependency with load disabled", "The temporary Length field is absent", "Final names and data types match the report fields"]),
        ],
        "click_path": ["Filter Quantity to non-null", "Remove the first four remaining header rows", "Assign final types", "Remove Length and rename the item fields", "Confirm Table002 load is disabled", "Close & Apply", "Build the item summary", "Reconcile Quantity 20 and Value AED 427.12"],
        "task": "Load the final receipt table, build the item summary and record the reconciliation controls.",
        "evidence": "A 17-row model table and a report reconciling to Quantity 20 and Value AED 427.12",
    },
    5: {
        "screen_title": "Build and inspect the model",
        "screens": [
            ("Star schema", "05-model-star-schema.png", "Model view showing a central fact table connected to descriptive dimensions.", ["Fact table sits at the transaction grain", "Dimensions filter the fact through one-to-many relationships", "A dedicated Date table supports consistent time analysis"]),
            ("Relationship paths", "05-model-relationships.png", "A more developed model showing active relationship paths across several tables.", ["Solid lines are active relationships", "Arrow direction shows filter propagation", "Technical bridge tables should solve a defined modelling problem"]),
        ],
        "click_path": ["Select Model view on the left rail", "Place fact tables centrally and dimensions around them", "Drag a unique dimension key to the matching fact foreign key", "Open relationship properties and verify cardinality and cross-filter direction", "Use Manage relationships to inspect inactive or ambiguous paths"],
        "task": "Create the Date, Product, Customer and Geography relationships, then test that each dimension filters Sales correctly.",
        "evidence": "A clean model diagram with one-to-many, single-direction relationships",
    },
    6: {
        "screen_title": "Write DAX in the formula bar",
        "screens": [
            ("DAX calculation", "06-dax-formula.png", "Model view with the DAX formula bar active while a calculated table is being defined.", ["The formula bar is where DAX is authored", "Field and table references must be unambiguous", "A calculation belongs in the model, not in a visual title or manual spreadsheet"]),
        ],
        "click_path": ["Modeling > New measure", "Enter a base measure such as Net Sales = SUM(Sales[NetAmount])", "Add Gross Margin and Gross Margin % using DIVIDE", "Place the measure in a table visual", "Apply country and date filters and confirm the result changes correctly"],
        "task": "Create Net Sales, Gross Margin, Margin %, Budget Variance and Prior Year Sales as explicit measures.",
        "evidence": "A measure table with business-friendly names, formats and validated totals",
    },
    7: {
        "screen_title": "Build a visual from the report canvas",
        "screens": [
            ("Visualizations pane", "07-visualizations-pane.jpeg", "A report visual selected with its field wells and available visual types visible.", ["Select visual type by analytical purpose", "Place fields in the correct wells", "Formatting should clarify hierarchy rather than decorate the page"]),
        ],
        "click_path": ["Select Report view", "Choose a visual from the Visualizations pane", "Drag dimensions and measures into the relevant field wells", "Sort, format numbers and write a question-led title", "Use Format > Edit interactions to test cross-filter behaviour"],
        "task": "Build one KPI, one monthly trend and one sorted category-variance visual. Explain why each visual fits its question.",
        "evidence": "A clean analysis page with consistent titles, units and accessible contrast",
    },
    8: {
        "screen_title": "Turn visuals into a report experience",
        "screens": [
            ("Multi-visual report page", "08-report-experience.png", "A completed report page combining KPIs, trends and drivers into a guided analytical view.", ["Headline values are visible first", "Trend and driver visuals answer natural follow-up questions", "Page and visual state should remain understandable after interaction"]),
        ],
        "click_path": ["Create Overview, Drivers and Transaction Detail pages", "Insert > Buttons > Navigator > Page navigator", "Add a drillthrough field to the detail page", "View > Bookmarks and Selection to create a Reset Filters state", "Test the path from headline KPI to underlying transactions"],
        "task": "Create a three-page navigation path and a drillthrough page that retains the selected entity context.",
        "evidence": "A report journey that moves from overview to driver to transaction evidence",
    },
    9: {
        "screen_title": "Read the M code behind the query",
        "screens": [
            ("Advanced Editor", "09-advanced-editor.jpeg", "The Power Query Advanced Editor displaying a let/in expression created from transformation steps.", ["Named expressions appear between let and in", "Each step can reference an earlier step", "The expression after in is the query result"]),
        ],
        "click_path": ["Power Query Editor > View > Advanced Editor", "Locate the let block and the expression after in", "Rename one generated step and observe the code change", "Home > Manage Parameters > New Parameter", "Replace the hard-coded source path with the parameter"],
        "task": "Parameterize the folder path and convert the repeated file-cleaning sequence into a reusable function.",
        "evidence": "A portable query with a readable let/in structure and no hard-coded learner path",
    },
    10: {
        "screen_title": "Review an audit analytics report",
        "screens": [
            ("Benford first-digit analysis", "10-benford-analysis.png", "A Power BI report comparing observed first-digit frequencies with the expected Benford distribution and listing transactions for review.", ["Observed and expected patterns are compared visually", "The transaction table supports investigation", "A deviation is a risk indicator, not a conclusion of fraud"]),
        ],
        "click_path": ["Create a First Digit column from absolute transaction amount", "Create observed count and observed percentage measures", "Create or relate an expected Benford table", "Plot observed and expected percentages by first digit", "Add drillthrough or a detail table for the flagged population"],
        "task": "Build the first-digit comparison and investigate the largest deviations using the supplied transaction detail.",
        "evidence": "A documented exception report with population rules and transaction-level evidence",
    },
    11: {
        "screen_title": "Configure refresh and security",
        "screens": [
            ("Gateway management", "11-gateway-settings.jpeg", "Power BI Service settings showing the gateway management entry point.", ["Gateways connect the Service to supported on-premises sources", "Refresh ownership and credentials require deliberate handover", "Gateway availability must be tested before go-live"]),
            ("Row-level security", "11-row-level-security.png", "A row-level security role being defined for a model table.", ["A role contains the filter rule", "Users or groups are assigned after publishing", "Use View as role in Desktop before distribution"]),
        ],
        "click_path": ["Desktop > Modeling > Manage roles and define the row filter", "Modeling > View as to test every role", "Home > Publish and choose the controlled workspace", "Service > semantic model settings > configure credentials and refresh", "Service > Security > assign the approved users or groups"],
        "task": "Design a regional-manager role and a deployment checklist covering workspace access, refresh owner and gateway dependency.",
        "evidence": "A tested RLS role and a practical deployment runbook",
    },
    12: {
        "screen_title": "Study the completed capstone pattern",
        "screens": [
            ("Management dashboard", "12-capstone-dashboard.png", "A completed Power BI dashboard combining KPIs, category analysis, maps, trends and detail views.", ["KPIs answer the opening management question", "Drivers and trends explain performance", "Detailed visuals preserve a path to evidence", "The whole page uses a consistent visual language"]),
        ],
        "click_path": ["Transform and reconcile the supplied source files", "Create the star schema and explicit measure pack", "Build Overview, Performance Drivers and Audit Exceptions pages", "Add navigation, drillthrough and reset interactions", "Reconcile control totals and present a five-minute recommendation"],
        "task": "Rebuild the capstone from the starter PBIX, then compare your choices with the reference solution only after validation.",
        "evidence": "A complete PBIX, reconciliation note and five-minute management presentation",
    },
}
